// ============================================================
// Opportune V4 — Comprehensive Mock Dataset
// Realistic, high-fidelity data across Jobs, Internships,
// Hackathons, Contests, Companies, Bookmarks & Applications.
// Used when backend API endpoint is not yet online or offline.
// ============================================================

import { Job } from '@/types/job';
import { Internship } from '@/types/internship';
import { Hackathon } from '@/types/hackathon';
import { Contest } from '@/types/contest';
import { Company, CompanyDetail } from '@/types/company';
import { Application } from '@/types/application';
import { Bookmark, BookmarkCollection, UserProfile } from '@/types/user';

export const MOCK_COMPANIES: CompanyDetail[] = [
  {
    id: 'comp-1',
    slug: 'google',
    name: 'Google',
    domain: 'google.com',
    logoUrl: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=128&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1579389083078-4e7018379f7e?w=1200&auto=format&fit=crop&q=80',
    industry: 'Technology / Internet',
    headquarters: 'Mountain View, CA & Bengaluru, India',
    size: '100,000+ employees',
    foundedYear: 1998,
    about: 'Google’s mission is to organize the world’s information and make it universally accessible and useful. We build products and services used by billions around the globe.',
    culture: 'Driven by curiosity, collaborative culture, deep technical exploration, and impact at global scale.',
    perks: ['Comprehensive healthcare', 'Annual wellness stipend', 'Continuous learning budget', 'Flexible hybrid policy'],
    websiteUrl: 'https://google.com',
    careersUrl: 'https://careers.google.com',
    socialLinks: {
      linkedin: 'https://linkedin.com/company/google',
      twitter: 'https://twitter.com/google',
      github: 'https://github.com/google',
      website: 'https://google.com',
      careers: 'https://careers.google.com',
    },
    stats: {
      openJobsCount: 14,
      openInternshipsCount: 5,
      hackathonsCount: 2,
      totalOpportunities: 21,
    },
    isVerified: true,
    isHiring: true,
    jobs: [],
    internships: [],
    hackathons: [],
  },
  {
    id: 'comp-2',
    slug: 'stripe',
    name: 'Stripe',
    domain: 'stripe.com',
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=1200&auto=format&fit=crop&q=80',
    industry: 'Financial Technology',
    headquarters: 'San Francisco, CA & Dublin, Ireland',
    size: '7,000+ employees',
    foundedYear: 2010,
    about: 'Stripe is a financial infrastructure platform for businesses. Millions of companies—from the world’s largest enterprises to the most ambitious startups—use Stripe to accept payments, grow their revenue, and accelerate new business opportunities.',
    culture: 'Obsessed with developer ergonomics, high bar for written communication, rigor, and speed.',
    perks: ['Remote-first culture', 'Competitive equity', 'Home office setup stipend', 'Health & wellness perks'],
    websiteUrl: 'https://stripe.com',
    careersUrl: 'https://stripe.com/jobs',
    socialLinks: {
      linkedin: 'https://linkedin.com/company/stripe',
      twitter: 'https://twitter.com/stripe',
      github: 'https://github.com/stripe',
      website: 'https://stripe.com',
      careers: 'https://stripe.com/jobs',
    },
    stats: {
      openJobsCount: 8,
      openInternshipsCount: 3,
      hackathonsCount: 1,
      totalOpportunities: 12,
    },
    isVerified: true,
    isHiring: true,
    jobs: [],
    internships: [],
    hackathons: [],
  },
  {
    id: 'comp-3',
    slug: 'postman',
    name: 'Postman',
    domain: 'postman.com',
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&auto=format&fit=crop&q=80',
    industry: 'Developer Tools',
    headquarters: 'San Francisco, CA & Bengaluru, India',
    size: '1,000+ employees',
    foundedYear: 2014,
    about: 'Postman is an API platform for building and using APIs. Postman simplifies each step of the API lifecycle and streamlines collaboration so you can create better APIs—faster.',
    culture: 'API-first mindset, global remote-first team, user centric, continuous iteration.',
    perks: ['Flexible working', 'Health benefits', 'Learning stipend', 'Top of the line equipment'],
    websiteUrl: 'https://postman.com',
    careersUrl: 'https://www.postman.com/careers',
    socialLinks: {
      linkedin: 'https://linkedin.com/company/postman-platform',
      twitter: 'https://twitter.com/getpostman',
      github: 'https://github.com/postmanlabs',
      website: 'https://postman.com',
      careers: 'https://www.postman.com/careers',
    },
    stats: {
      openJobsCount: 6,
      openInternshipsCount: 2,
      hackathonsCount: 1,
      totalOpportunities: 9,
    },
    isVerified: true,
    isHiring: true,
    jobs: [],
    internships: [],
    hackathons: [],
  },
  {
    id: 'comp-4',
    slug: 'razorpay',
    name: 'Razorpay',
    domain: 'razorpay.com',
    logoUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=128&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=80',
    industry: 'FinTech / Payments',
    headquarters: 'Bengaluru, Karnataka, India',
    size: '3,000+ employees',
    foundedYear: 2014,
    about: 'Razorpay is India’s first full-stack financial solutions company powering payments, banking, credit, and payroll for businesses of all sizes.',
    culture: 'High ownership, innovation speed, bold experimentation, engineering excellence.',
    perks: ['Comprehensive health cover', 'ESOP grants', 'Free gourmet meals', 'Cab reimbursement'],
    websiteUrl: 'https://razorpay.com',
    careersUrl: 'https://razorpay.com/jobs',
    socialLinks: {
      linkedin: 'https://linkedin.com/company/razorpay',
      twitter: 'https://twitter.com/razorpay',
      github: 'https://github.com/razorpay',
      website: 'https://razorpay.com',
      careers: 'https://razorpay.com/jobs',
    },
    stats: {
      openJobsCount: 11,
      openInternshipsCount: 4,
      hackathonsCount: 2,
      totalOpportunities: 17,
    },
    isVerified: true,
    isHiring: true,
    jobs: [],
    internships: [],
    hackathons: [],
  },
];

export const MOCK_JOBS: Job[] = [
  {
    id: 'job-1',
    slug: 'senior-frontend-engineer-react-stripe',
    title: 'Senior Frontend Engineer (React / TypeScript)',
    company: {
      id: 'comp-2',
      name: 'Stripe',
      slug: 'stripe',
      logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
      websiteUrl: 'https://stripe.com',
      verified: true,
      industry: 'FinTech',
      location: 'Bengaluru / Remote',
    },
    location: 'Bengaluru, India (Remote Available)',
    country: 'India',
    city: 'Bengaluru',
    workplaceType: 'hybrid',
    employmentType: 'full-time',
    seniority: 'senior',
    experienceYears: { min: 4, max: 8 },
    salary: {
      min: 3600000,
      max: 5200000,
      currency: 'INR',
      period: 'year',
      formatted: '₹36,00,000 – ₹52,00,000 / yr',
    },
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'GraphQL', 'Web Performance'],
    description: `Stripe is looking for a Senior Frontend Engineer to build world-class merchant checkout flows and banking dashboard interfaces. You will work on design system components, high-traffic payment widgets, and accessible, responsive interfaces used by millions worldwide.`,
    responsibilities: [
      'Design, build, and maintain high-performance, resilient UI components.',
      'Collaborate closely with product designers, backend teams, and accessibility engineers.',
      'Optimize core web vitals and client-side rendering pipelines for sub-second interactions.',
      'Mentor intermediate and junior frontend engineers in software architecture.',
    ],
    requirements: [
      '4+ years of professional production experience with React, TypeScript, and modern state management.',
      'Deep understanding of browser internals, rendering cycles, accessibility (WCAG), and responsive CSS.',
      'Track record of building complex, user-facing applications at scale.',
    ],
    benefits: [
      'Top-tier competitive base salary + equity compensation',
      'Full healthcare insurance for employee + family',
      'Home office setup and internet allowances',
      'Annual learning and conference budget',
    ],
    postedAt: '2026-09-28T09:00:00Z',
    applyUrl: 'https://stripe.com/jobs/senior-frontend-engineer',
    sourcePlatform: 'Stripe Careers',
    isFeatured: true,
    isBookmarked: false,
    hasApplied: false,
    applicantsCount: 68,
  },
  {
    id: 'job-2',
    slug: 'software-engineer-backend-python-google',
    title: 'Software Engineer III — Cloud Infrastructure',
    company: {
      id: 'comp-1',
      name: 'Google',
      slug: 'google',
      logoUrl: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=128&auto=format&fit=crop&q=80',
      websiteUrl: 'https://google.com',
      verified: true,
      industry: 'Technology',
      location: 'Bengaluru / Hyderabad',
    },
    location: 'Bengaluru, Karnataka, India',
    country: 'India',
    city: 'Bengaluru',
    workplaceType: 'hybrid',
    employmentType: 'full-time',
    seniority: 'mid',
    experienceYears: { min: 3, max: 6 },
    salary: {
      min: 4200000,
      max: 6000000,
      currency: 'INR',
      period: 'year',
      formatted: '₹42,00,000 – ₹60,00,000 / yr',
    },
    skills: ['Python', 'Go', 'Kubernetes', 'Distributed Systems', 'GCP'],
    description: `As a Software Engineer in Google Cloud, you will handle petabyte-scale distributed data pipelines, design low-latency RPC interfaces, and architect mission-critical storage components.`,
    responsibilities: [
      'Design, implement, test, and maintain distributed backend microservices.',
      'Analyze and optimize service bottlenecks, scaling limits, and fault recovery.',
      'Coordinate with global site reliability and storage platform teams.',
    ],
    requirements: [
      '3+ years of experience with Python, Go, Java or C++ in distributed environments.',
      'Strong grasp of concurrency, networking protocols, databases, and microservices.',
      'Bachelor’s or Master’s in Computer Science or equivalent practical experience.',
    ],
    benefits: [
      'Comprehensive medical, dental, and vision insurance',
      'Free gourmet meals and campus micro-kitchens',
      'Stock options (GSUs) with quarterly vesting',
    ],
    postedAt: '2026-09-30T14:30:00Z',
    applyUrl: 'https://careers.google.com/jobs/results/12345',
    sourcePlatform: 'Google Careers',
    isFeatured: true,
    isBookmarked: true,
    hasApplied: false,
    applicantsCount: 142,
  },
  {
    id: 'job-3',
    slug: 'fullstack-engineer-razorpay',
    title: 'Fullstack Engineer — Core Banking Platform',
    company: {
      id: 'comp-4',
      name: 'Razorpay',
      slug: 'razorpay',
      logoUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=128&auto=format&fit=crop&q=80',
      websiteUrl: 'https://razorpay.com',
      verified: true,
      industry: 'FinTech',
      location: 'Bengaluru, India',
    },
    location: 'Bengaluru, India',
    country: 'India',
    city: 'Bengaluru',
    workplaceType: 'onsite',
    employmentType: 'full-time',
    seniority: 'mid',
    experienceYears: { min: 2, max: 5 },
    salary: {
      min: 2400000,
      max: 3500000,
      currency: 'INR',
      period: 'year',
      formatted: '₹24,00,000 – ₹35,00,000 / yr',
    },
    skills: ['Node.js', 'React', 'PostgreSQL', 'Kafka', 'Redis'],
    description: `RazorpayX is revolutionizing business banking in India. As a fullstack engineer on this team, you will craft merchant accounting workflows, payout orchestration layers, and real-time ledger engines.`,
    responsibilities: [
      'Architect robust APIs and clean React micro-frontends.',
      'Work with financial transaction models ensuring idempotent operations and strict consistency.',
    ],
    requirements: [
      'Strong foundation in JavaScript/TypeScript (React + Node.js).',
      'Relational database design skills with PostgreSQL or MySQL.',
    ],
    benefits: ['Competitive salary + generous ESOP package', 'Health insurance', 'Learning reimbursements'],
    postedAt: '2026-10-01T08:15:00Z',
    applyUrl: 'https://razorpay.com/jobs/fullstack-banking',
    sourcePlatform: 'Razorpay Careers',
    isFeatured: false,
    isBookmarked: false,
    hasApplied: true,
    applicantsCount: 45,
  },
  {
    id: 'job-4',
    slug: 'api-platform-engineer-postman',
    title: 'API Platform Engineer (Developer Tools)',
    company: {
      id: 'comp-3',
      name: 'Postman',
      slug: 'postman',
      logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
      websiteUrl: 'https://postman.com',
      verified: true,
      industry: 'Developer Tools',
      location: 'Remote (India)',
    },
    location: 'Remote (India)',
    country: 'India',
    workplaceType: 'remote',
    employmentType: 'full-time',
    seniority: 'entry',
    experienceYears: { min: 1, max: 3 },
    salary: {
      min: 1800000,
      max: 2600000,
      currency: 'INR',
      period: 'year',
      formatted: '₹18,00,000 – ₹26,00,000 / yr',
    },
    skills: ['TypeScript', 'Node.js', 'Electron', 'REST', 'WebSockets'],
    description: `Help build the next generation of Postman client runtime. You'll contribute to our open protocol engine, sync protocols, and developer debugging interfaces.`,
    responsibilities: ['Build features for Postman desktop and web client runtime.'],
    requirements: ['1+ years hands-on with TypeScript and asynchronous programming.'],
    benefits: ['100% remote flexibility', 'Generous home office allowance'],
    postedAt: '2026-10-02T06:00:00Z',
    applyUrl: 'https://www.postman.com/careers/platform-engineer',
    sourcePlatform: 'Postman Careers',
    isFeatured: false,
    isBookmarked: false,
    hasApplied: false,
    applicantsCount: 89,
  },
];

export const MOCK_INTERNSHIPS: Internship[] = [
  {
    id: 'intern-1',
    slug: 'software-engineering-intern-google-summer-2027',
    title: 'Software Engineering Intern — Summer 2027',
    company: {
      id: 'comp-1',
      name: 'Google',
      slug: 'google',
      logoUrl: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=128&auto=format&fit=crop&q=80',
      websiteUrl: 'https://google.com',
      verified: true,
      industry: 'Technology',
      location: 'Bengaluru / Hyderabad',
    },
    location: 'Bengaluru / Hyderabad, India',
    country: 'India',
    city: 'Bengaluru',
    workplaceType: 'hybrid',
    stipend: {
      min: 110000,
      max: 130000,
      currency: 'INR',
      period: 'month',
      formatted: '₹1,20,000 / month',
    },
    duration: {
      value: 3,
      unit: 'months',
      formatted: '3 months (May – July)',
    },
    startDate: '2027-05-15',
    isImmediate: false,
    applicationDeadline: '2026-11-15T23:59:59Z',
    skills: ['C++', 'Python', 'Java', 'Data Structures', 'Algorithms'],
    description: `Join Google as a Software Engineering Intern! You will work alongside experienced Google engineers on real-world systems, contributing code that impacts millions of daily active users across Search, Android, YouTube, or Cloud.`,
    perks: ['Pre-placement offer (PPO) possibility based on performance', 'Free meals and gym access', 'Relocation & housing assistance'],
    ppoOffered: true,
    eligibility: ['Enrolled in a Bachelor’s or Master’s in Computer Science or related degree', 'Graduating in 2027 or 2028'],
    responsibilities: [
      'Develop product features and internal tooling.',
      'Participate in design reviews and unit testing.',
      'Present internship project findings to product leadership.',
    ],
    postedAt: '2026-09-25T10:00:00Z',
    applyUrl: 'https://careers.google.com/jobs/intern-swe-2027',
    sourcePlatform: 'Google Careers',
    isFeatured: true,
    isBookmarked: true,
    hasApplied: false,
    applicantsCount: 310,
  },
  {
    id: 'intern-2',
    slug: 'frontend-engineering-intern-stripe',
    title: 'Frontend Engineering Intern (Design Systems & React)',
    company: {
      id: 'comp-2',
      name: 'Stripe',
      slug: 'stripe',
      logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
      websiteUrl: 'https://stripe.com',
      verified: true,
      industry: 'FinTech',
      location: 'Remote (India)',
    },
    location: 'Remote (India)',
    country: 'India',
    workplaceType: 'remote',
    stipend: {
      min: 80000,
      max: 95000,
      currency: 'INR',
      period: 'month',
      formatted: '₹90,000 / month',
    },
    duration: {
      value: 6,
      unit: 'months',
      formatted: '6 months',
    },
    startDate: 'immediate',
    isImmediate: true,
    applicationDeadline: '2026-10-25T23:59:59Z',
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'Framer Motion'],
    description: `Work with Stripe’s design systems and UI platform team. You'll build polished, accessible UI primitives and documentation interactive previews.`,
    perks: ['PPO Opportunity for exceptional interns', 'Hardware provided (MacBook Pro)', 'Mentorship by staff engineers'],
    ppoOffered: true,
    eligibility: ['Final year students or recent graduates', 'Demonstrated personal projects or open source contributions'],
    postedAt: '2026-09-29T12:00:00Z',
    applyUrl: 'https://stripe.com/jobs/frontend-intern',
    sourcePlatform: 'Stripe Careers',
    isFeatured: true,
    isBookmarked: false,
    hasApplied: false,
    applicantsCount: 154,
  },
  {
    id: 'intern-3',
    slug: 'backend-developer-intern-razorpay',
    title: 'Backend Developer Intern — Payments Gateway',
    company: {
      id: 'comp-4',
      name: 'Razorpay',
      slug: 'razorpay',
      logoUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=128&auto=format&fit=crop&q=80',
      websiteUrl: 'https://razorpay.com',
      verified: true,
      industry: 'FinTech',
      location: 'Bengaluru, India',
    },
    location: 'Bengaluru, Karnataka',
    country: 'India',
    city: 'Bengaluru',
    workplaceType: 'onsite',
    stipend: {
      min: 45000,
      max: 60000,
      currency: 'INR',
      period: 'month',
      formatted: '₹50,000 / month',
    },
    duration: {
      value: 6,
      unit: 'months',
      formatted: '6 months',
    },
    startDate: '2027-01-05',
    isImmediate: false,
    applicationDeadline: '2026-11-05T18:00:00Z',
    skills: ['Node.js', 'Go', 'MySQL', 'Redis'],
    description: `Gain practical experience building high-throughput payment processing APIs, webhook dispatch systems, and bank settlement pipelines.`,
    perks: ['PPO Consideration', 'Daily catered breakfast & lunch', 'Certificate of Completion'],
    ppoOffered: true,
    eligibility: ['B.Tech / B.E. in CS/IT or related branch graduating in 2027'],
    postedAt: '2026-10-01T11:00:00Z',
    applyUrl: 'https://razorpay.com/jobs/backend-intern',
    sourcePlatform: 'Razorpay Careers',
    isFeatured: false,
    isBookmarked: false,
    hasApplied: false,
    applicantsCount: 92,
  },
];

export const MOCK_HACKATHONS: Hackathon[] = [
  {
    id: 'hack-1',
    slug: 'ai-innovation-hackathon-2026',
    title: 'AI Innovation Global Hackathon',
    organizer: {
      name: 'Google Cloud & Anthropic',
      logoUrl: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=128&auto=format&fit=crop&q=80',
      websiteUrl: 'https://cloud.google.com',
      verified: true,
    },
    mode: 'online',
    location: 'Virtual / Online Worldwide',
    registrationDeadline: '2026-10-18T23:59:59Z',
    startDate: '2026-10-20T00:00:00Z',
    endDate: '2026-10-25T23:59:59Z',
    prizePool: {
      total: 500000,
      currency: 'INR',
      formatted: '₹5,00,000',
      prizes: [
        { title: '1st Place Winner', amount: 250000, currency: 'INR', description: 'Cash prize + $10k Google Cloud credits + fast-track interview' },
        { title: '2nd Place Runner Up', amount: 150000, currency: 'INR', description: 'Cash prize + $5k credits' },
        { title: 'Best Use of Generative AI', amount: 100000, currency: 'INR', description: 'Special category track prize' },
      ],
    },
    teamSize: {
      min: 2,
      max: 4,
      formatted: '2–4 members',
    },
    eligibility: 'Open to developers, students, researchers, and startups worldwide.',
    themes: ['Generative AI', 'Agentic Workflows', 'Developer Productivity', 'Healthcare AI'],
    technologies: ['Gemini API', 'Claude API', 'Python', 'React', 'LangChain', 'FastAPI'],
    tags: ['AI', 'ML', 'GenAI', 'LLM', 'Global'],
    description: `Build cutting-edge generative AI applications that solve real-world problems. Whether it's autonomous multi-agent systems, multimodal search, or developer tooling, showcase what modern intelligence can achieve.`,
    rules: [
      'All code must be written during the hackathon period.',
      'Projects must utilize at least one AI LLM or multimodal API.',
      'Teams must submit a working GitHub repository and 3-minute video demo.',
    ],
    timeline: [
      { title: 'Registration Opens', date: 'Oct 01, 2026', completed: true },
      { title: 'Registration Closes', date: 'Oct 18, 2026', completed: false },
      { title: 'Hacking Begins & Opening Ceremony', date: 'Oct 20, 2026', completed: false },
      { title: 'Project Submission Deadline', date: 'Oct 25, 2026', completed: false },
      { title: 'Winners Announcement', date: 'Oct 28, 2026', completed: false },
    ],
    sponsors: [
      { name: 'Google Cloud', tier: 'title' },
      { name: 'Vercel', tier: 'platinum' },
      { name: 'GitHub', tier: 'gold' },
    ],
    faqs: [
      { question: 'Is participation free?', answer: 'Yes, 100% free with complimentary API credits provided to all registered teams.' },
      { question: 'Can I participate solo?', answer: 'This hackathon requires collaborative teams of 2 to 4 members. You can find teammates in our Discord.' },
    ],
    status: 'open',
    applyUrl: 'https://ai-innovation-hackathon.devpost.com',
    officialUrl: 'https://ai-innovation-hackathon.devpost.com',
    bannerUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&auto=format&fit=crop&q=80',
    sourcePlatform: 'Devpost',
    isFeatured: true,
    isBookmarked: true,
    participantsCount: 1420,
    viewsCount: 9800,
  },
  {
    id: 'hack-2',
    slug: 'ethindia-web3-hackathon-2026',
    title: 'ETHIndia 2026 — Asia’s Biggest Ethereum Hackathon',
    organizer: {
      name: 'Devfolio & Ethereum Foundation',
      logoUrl: 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?w=128&auto=format&fit=crop&q=80',
      websiteUrl: 'https://ethindia.co',
      verified: true,
    },
    mode: 'offline',
    location: 'KTPO, Bengaluru, India',
    city: 'Bengaluru',
    country: 'India',
    registrationDeadline: '2026-11-10T23:59:59Z',
    startDate: '2026-12-04T09:00:00Z',
    endDate: '2026-12-06T18:00:00Z',
    prizePool: {
      total: 15000000,
      currency: 'INR',
      formatted: '₹1,50,00,000+',
      prizes: [
        { title: 'Grand Winner', amount: 5000000, currency: 'INR' },
        { title: 'Bounty Tracks (Polygon, Arbitrum, Base, Uniswap)', amount: 10000000, currency: 'INR' },
      ],
    },
    teamSize: {
      min: 1,
      max: 4,
      formatted: '1–4 members',
    },
    eligibility: 'Open to builders, designers, and smart contract engineers.',
    themes: ['Web3', 'Zero Knowledge', 'DeFi', 'Account Abstraction', 'Decentralized Social'],
    technologies: ['Solidity', 'Foundry', 'Next.js', 'Ethers.js', 'Rust'],
    tags: ['Web3', 'Ethereum', 'DeFi', 'ZK', 'In-Person'],
    description: `ETHIndia brings together 2,000+ top hackers from across the world to build the decentralized future over 36 hours of non-stop innovation.`,
    status: 'open',
    applyUrl: 'https://ethindia.co/apply',
    officialUrl: 'https://ethindia.co',
    bannerUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=1200&auto=format&fit=crop&q=80',
    sourcePlatform: 'Devfolio',
    isFeatured: true,
    isBookmarked: false,
    participantsCount: 3400,
    viewsCount: 22000,
  },
  {
    id: 'hack-3',
    slug: 'hackerearth-fintech-sprint',
    title: 'FinTech Revolution Sprint',
    organizer: {
      name: 'Razorpay & HackerEarth',
      logoUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=128&auto=format&fit=crop&q=80',
      websiteUrl: 'https://hackerearth.com',
      verified: true,
    },
    mode: 'hybrid',
    location: 'Mumbai & Online',
    city: 'Mumbai',
    country: 'India',
    registrationDeadline: '2026-10-12T18:00:00Z',
    startDate: '2026-10-14T10:00:00Z',
    endDate: '2026-10-16T20:00:00Z',
    prizePool: {
      total: 350000,
      currency: 'INR',
      formatted: '₹3,50,000',
    },
    teamSize: {
      min: 1,
      max: 3,
      formatted: '1–3 members',
    },
    eligibility: 'Students and working professionals.',
    themes: ['Digital Payments', 'Fraud Prevention', 'Cross-border remittances'],
    technologies: ['Node.js', 'React', 'Python', 'PostgreSQL'],
    tags: ['FinTech', 'Payments', 'Security'],
    description: `Develop innovative solutions tackling next-generation consumer checkout friction, biometric auth, and merchant fraud detection.`,
    status: 'closing-soon',
    applyUrl: 'https://hackerearth.com/challenges/hackathon/fintech-sprint',
    officialUrl: 'https://hackerearth.com',
    sourcePlatform: 'HackerEarth',
    isFeatured: false,
    isBookmarked: false,
    participantsCount: 880,
  },
];

export const MOCK_CONTESTS: Contest[] = [
  {
    id: 'contest-1',
    slug: 'codechef-starters-210',
    name: 'Starters 210 (Rated for Div 2, 3 & 4)',
    platform: 'CodeChef',
    platformLogoUrl: 'https://cdn.codechef.com/images/cc-logo.svg',
    startTime: '2026-10-05T20:00:00+05:30',
    endTime: '2026-10-05T22:00:00+05:30',
    durationMinutes: 120,
    durationFormatted: '2 hours',
    ratingType: 'Rated',
    difficulty: 'intermediate',
    participantsCount: 14500,
    status: 'UPCOMING',
    eligibility: 'Rated for Divisions 2, 3, and 4 (Rating < 2000)',
    officialUrl: 'https://www.codechef.com/START210',
    description: 'Weekly algorithmic contest with 6 to 8 problems ranging from easy fundamentals to dynamic programming and graph algorithms.',
    problemCount: 8,
    languagesAllowed: ['C++', 'Python', 'Java', 'Kotlin', 'Go'],
    isBookmarked: true,
  },
  {
    id: 'contest-2',
    slug: 'codeforces-round-998-div2',
    name: 'Codeforces Round 998 (Div. 2)',
    platform: 'Codeforces',
    startTime: '2026-10-07T20:05:00+05:30',
    endTime: '2026-10-07T22:05:00+05:30',
    durationMinutes: 120,
    durationFormatted: '2 hours',
    ratingType: 'Div 2',
    difficulty: 'advanced',
    participantsCount: 22000,
    status: 'UPCOMING',
    eligibility: 'Rated for Division 2 participants (Rating < 2100)',
    officialUrl: 'https://codeforces.com/contest/998',
    description: 'Premier competitive programming contest featuring rigorous time limits, corner cases, and mathematical reasoning.',
    problemCount: 6,
    languagesAllowed: ['GNU C++20', 'PyPy 3', 'Java 21'],
    isBookmarked: false,
  },
  {
    id: 'contest-3',
    slug: 'leetcode-weekly-contest-420',
    name: 'LeetCode Weekly Contest 420',
    platform: 'LeetCode',
    startTime: '2026-10-04T08:00:00+05:30',
    endTime: '2026-10-04T09:30:00+05:30',
    durationMinutes: 90,
    durationFormatted: '1 hour 30 mins',
    ratingType: 'Rated',
    difficulty: 'all-levels',
    participantsCount: 35000,
    status: 'UPCOMING',
    eligibility: 'Open to all registered LeetCode members',
    officialUrl: 'https://leetcode.com/contest/weekly-contest-420',
    description: '4 algorithm questions (1 Easy, 2 Medium, 1 Hard). Perfect for technical interview practice and global ranking.',
    problemCount: 4,
    languagesAllowed: ['C++', 'Python3', 'Java', 'JavaScript', 'TypeScript', 'Rust', 'Go'],
    isBookmarked: false,
  },
  {
    id: 'contest-4',
    slug: 'atcoder-beginner-contest-380',
    name: 'AtCoder Beginner Contest 380 (ABC 380)',
    platform: 'AtCoder',
    startTime: '2026-10-03T17:30:00+05:30',
    endTime: '2026-10-03T19:10:00+05:30',
    durationMinutes: 100,
    durationFormatted: '100 mins',
    ratingType: 'Rated',
    difficulty: 'beginner',
    participantsCount: 11000,
    status: 'LIVE',
    eligibility: 'Rated for participants with rating < 2000',
    officialUrl: 'https://atcoder.jp/contests/abc380',
    description: 'High-quality Japanese problem set with clear mathematical formulation and fast automated grading.',
    problemCount: 7,
    languagesAllowed: ['C++23', 'Python3', 'Rust', 'Java'],
    isBookmarked: false,
  },
  {
    id: 'contest-5',
    slug: 'geeksforgeeks-weekly-160',
    name: 'GeeksforGeeks Weekly Coding Contest 160',
    platform: 'GeeksforGeeks',
    startTime: '2026-09-28T19:00:00+05:30',
    endTime: '2026-09-28T20:30:00+05:30',
    durationMinutes: 90,
    durationFormatted: '1 hour 30 mins',
    ratingType: 'Rated',
    difficulty: 'intermediate',
    participantsCount: 8200,
    status: 'COMPLETED',
    eligibility: 'All students & professionals',
    officialUrl: 'https://practice.geeksforgeeks.org/contest/weekly-contest-160',
    description: 'Industry-oriented algorithmic questions with immediate leaderboard rankings.',
    problemCount: 3,
    isBookmarked: false,
  },
];

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: 'app-1',
    userId: 'user-demo-1',
    opportunityId: 'job-3',
    opportunityType: 'job',
    opportunityTitle: 'Fullstack Engineer — Core Banking Platform',
    opportunitySlug: 'fullstack-engineer-razorpay',
    companyName: 'Razorpay',
    companyLogoUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=128&auto=format&fit=crop&q=80',
    location: 'Bengaluru, India',
    workplaceType: 'Onsite',
    status: 'interview',
    appliedDate: '2026-09-18T10:00:00Z',
    updatedAt: '2026-09-29T14:00:00Z',
    interviewDate: '2026-10-06T15:00:00Z',
    compensation: '₹28,00,000 / yr',
    notes: [
      { id: 'note-1', createdAt: '2026-09-20T11:00:00Z', content: 'HR screening call completed. Moving to technical round.' },
      { id: 'note-2', createdAt: '2026-09-29T14:00:00Z', content: 'System design scheduled for next Tuesday at 3:00 PM.' },
    ],
    timeline: [
      { status: 'applied', timestamp: '2026-09-18T10:00:00Z', note: 'Submitted resume via career page' },
      { status: 'screening', timestamp: '2026-09-20T11:00:00Z', note: 'Passed recruiter phone screen' },
      { status: 'interview', timestamp: '2026-09-29T14:00:00Z', note: 'Invited to Round 2 technical' },
    ],
  },
  {
    id: 'app-2',
    userId: 'user-demo-1',
    opportunityId: 'intern-1',
    opportunityType: 'internship',
    opportunityTitle: 'Software Engineering Intern — Summer 2027',
    opportunitySlug: 'software-engineering-intern-google-summer-2027',
    companyName: 'Google',
    companyLogoUrl: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=128&auto=format&fit=crop&q=80',
    location: 'Bengaluru / Hyderabad, India',
    workplaceType: 'Hybrid',
    status: 'applied',
    appliedDate: '2026-09-26T16:00:00Z',
    updatedAt: '2026-09-26T16:00:00Z',
    timeline: [
      { status: 'applied', timestamp: '2026-09-26T16:00:00Z', note: 'Application submitted with referral' },
    ],
  },
  {
    id: 'app-3',
    userId: 'user-demo-1',
    opportunityId: 'job-1',
    opportunityType: 'job',
    opportunityTitle: 'Senior Frontend Engineer (React / TypeScript)',
    opportunitySlug: 'senior-frontend-engineer-react-stripe',
    companyName: 'Stripe',
    companyLogoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
    location: 'Bengaluru / Remote',
    workplaceType: 'Hybrid',
    status: 'saved',
    appliedDate: '2026-09-28T12:00:00Z',
    updatedAt: '2026-09-28T12:00:00Z',
    timeline: [
      { status: 'saved', timestamp: '2026-09-28T12:00:00Z', note: 'Added to wishlist for application drafting' },
    ],
  },
];

export const MOCK_BOOKMARKS: Bookmark[] = [
  {
    id: 'bm-1',
    userId: 'user-demo-1',
    category: 'jobs',
    targetId: 'job-2',
    targetSlug: 'software-engineer-backend-python-google',
    title: 'Software Engineer III — Cloud Infrastructure',
    organization: 'Google',
    logoUrl: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=128&auto=format&fit=crop&q=80',
    location: 'Bengaluru, India',
    meta: { salary: '₹42L – ₹60L', seniority: 'Mid-Level' },
    savedAt: '2026-10-01T10:00:00Z',
  },
  {
    id: 'bm-2',
    userId: 'user-demo-1',
    category: 'internships',
    targetId: 'intern-1',
    targetSlug: 'software-engineering-intern-google-summer-2027',
    title: 'Software Engineering Intern — Summer 2027',
    organization: 'Google',
    logoUrl: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=128&auto=format&fit=crop&q=80',
    location: 'Bengaluru / Hyderabad',
    meta: { stipend: '₹1,20,000 / mo', duration: '3 months' },
    savedAt: '2026-09-29T18:00:00Z',
  },
  {
    id: 'bm-3',
    userId: 'user-demo-1',
    category: 'hackathons',
    targetId: 'hack-1',
    targetSlug: 'ai-innovation-hackathon-2026',
    title: 'AI Innovation Global Hackathon',
    organization: 'Google Cloud & Anthropic',
    logoUrl: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=128&auto=format&fit=crop&q=80',
    location: 'Virtual / Online',
    meta: { prize: '₹5,00,000', deadline: 'Oct 18, 2026' },
    savedAt: '2026-10-02T04:00:00Z',
  },
  {
    id: 'bm-4',
    userId: 'user-demo-1',
    category: 'contests',
    targetId: 'contest-1',
    targetSlug: 'codechef-starters-210',
    title: 'Starters 210',
    organization: 'CodeChef',
    logoUrl: null,
    meta: { starts: 'Oct 5, 8:00 PM', duration: '2 hours', platform: 'CodeChef' },
    savedAt: '2026-10-02T05:00:00Z',
  },
];

export const MOCK_COLLECTIONS: BookmarkCollection[] = [
  {
    id: 'col-1',
    name: 'Top Job Search',
    description: 'High-growth tech companies and high compensation roles',
    category: 'jobs',
    bookmarksCount: 4,
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'col-2',
    name: 'Summer Internships',
    description: 'Off-campus and on-campus 2027 software internship applications',
    category: 'internships',
    bookmarksCount: 3,
    createdAt: '2026-09-10T00:00:00Z',
  },
  {
    id: 'col-3',
    name: 'Flagship Hackathons',
    description: 'Major prize pool hackathons to compete in with team',
    category: 'hackathons',
    bookmarksCount: 2,
    createdAt: '2026-09-15T00:00:00Z',
  },
  {
    id: 'col-4',
    name: 'Weekly Contests',
    description: 'Rating booster rounds on CodeChef & LeetCode',
    category: 'contests',
    bookmarksCount: 2,
    createdAt: '2026-09-20T00:00:00Z',
  },
];

export const MOCK_USER_PROFILE: UserProfile = {
  id: 'user-demo-1',
  email: 'alex.developer@example.com',
  fullName: 'Alex Morgan',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=256&auto=format&fit=crop&q=80',
  headline: 'Fullstack & Systems Engineer | Open Source Enthusiast',
  bio: 'Building reactive, high-scale web products. Active competitive programmer and hackathon builder.',
  location: 'Bengaluru, India',
  phone: '+91 98765 43210',
  githubUrl: 'https://github.com/alexmorgan',
  linkedinUrl: 'https://linkedin.com/in/alexmorgan',
  portfolioUrl: 'https://alexmorgan.dev',
  resumeUrl: 'https://example.com/alex_resume.pdf',
  skills: ['React', 'TypeScript', 'Node.js', 'Python', 'Go', 'PostgreSQL', 'Tailwind CSS', 'Docker'],
  experiences: [
    {
      id: 'exp-1',
      role: 'Frontend Engineer',
      company: 'TechFlow Solutions',
      startDate: '2024-07-01',
      isCurrent: true,
      description: 'Building micro-frontends with React 19, TypeScript, and TanStack Query.',
    },
    {
      id: 'exp-2',
      role: 'Software Intern',
      company: 'DataPulse Inc.',
      startDate: '2023-12-01',
      endDate: '2024-06-30',
      description: 'Engineered analytics dashboards and optimized SQL query latency by 45%.',
    },
  ],
  education: [
    {
      id: 'edu-1',
      degree: 'B.Tech in Computer Science & Engineering',
      fieldOfStudy: 'Computer Science',
      institution: 'National Institute of Technology',
      startYear: 2021,
      endYear: 2025,
      grade: '8.9 CGPA',
    },
  ],
  preferences: {
    opportunityCategories: ['jobs', 'internships', 'hackathons', 'contests'],
    preferredLocations: ['Bengaluru', 'Mumbai', 'Remote (India)', 'Remote (Worldwide)'],
    preferredJobTypes: ['full-time', 'contract'],
    preferredTechnologies: ['React', 'TypeScript', 'Python', 'Node.js', 'Go'],
    workplacePreference: ['remote', 'hybrid'],
    emailAlerts: true,
    weeklyDigest: true,
    theme: 'system',
  },
  createdAt: '2026-01-15T00:00:00Z',
  updatedAt: '2026-10-01T12:00:00Z',
};
