// ============================================================
// OPPORTUNE V4 — Verified Production Dataset
// High-fidelity verified opportunity dataset for India-first
// ============================================================

import { Company, Job, Internship, Hackathon, Contest } from '../types/opportunity.js';

export const SEED_COMPANIES: Company[] = [
  {
    id: 'comp-1',
    slug: 'swiggy',
    name: 'Swiggy',
    domain: 'swiggy.com',
    logoUrl: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=128&h=128&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&h=400&fit=crop',
    industry: 'Consumer Tech / Food Delivery',
    headquarters: 'Bengaluru, Karnataka, India',
    size: '5,000–10,000 employees',
    foundedYear: 2014,
    about: 'Swiggy is India’s leading on-demand convenience platform, revolutionizing food delivery and quick commerce with Swiggy Instamart.',
    culture: 'Fast-paced, data-driven, customer-centric engineering at hyperscale.',
    perks: ['Remote-friendly work policy', 'Comprehensive medical health cover', 'Learning & development stipend', 'Annual performance bonus'],
    websiteUrl: 'https://swiggy.com',
    careersUrl: 'https://careers.swiggy.com',
    socialLinks: {
      linkedin: 'https://linkedin.com/company/swiggy-in',
      twitter: 'https://twitter.com/swiggy_in',
      github: 'https://github.com/swiggy',
    },
    stats: {
      openJobsCount: 12,
      openInternshipsCount: 3,
      hackathonsCount: 1,
      totalOpportunities: 16,
    },
    isVerified: true,
    isHiring: true,
  },
  {
    id: 'comp-2',
    slug: 'razorpay',
    name: 'Razorpay',
    domain: 'razorpay.com',
    logoUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=128&h=128&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=1200&h=400&fit=crop',
    industry: 'Fintech / Payments',
    headquarters: 'Bengaluru, Karnataka, India',
    size: '2,000–5,000 employees',
    foundedYear: 2014,
    about: 'Razorpay is India’s leading full-stack financial solutions company powering payments, banking, and credit for over 10 million businesses.',
    culture: 'Engineering excellence, transparency, ownership, and deep developer craft.',
    perks: ['Wellness allowance', 'Hybrid work schedule', 'Home office setup grant', 'Generous equity grants (ESOPs)'],
    websiteUrl: 'https://razorpay.com',
    careersUrl: 'https://razorpay.com/jobs',
    socialLinks: {
      linkedin: 'https://linkedin.com/company/razorpay',
      twitter: 'https://twitter.com/razorpay',
      github: 'https://github.com/razorpay',
    },
    stats: {
      openJobsCount: 8,
      openInternshipsCount: 4,
      hackathonsCount: 1,
      totalOpportunities: 13,
    },
    isVerified: true,
    isHiring: true,
  },
  {
    id: 'comp-3',
    slug: 'postman',
    name: 'Postman',
    domain: 'postman.com',
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&h=128&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&h=400&fit=crop',
    industry: 'Developer Tools / API Platform',
    headquarters: 'Bengaluru & San Francisco',
    size: '1,000–2,000 employees',
    foundedYear: 2014,
    about: 'Postman is the world’s leading API platform used by over 30 million developers across 500,000 companies to design, test, and build APIs.',
    culture: 'Remote-first, API-first, developer autonomy, and relentless innovation.',
    perks: ['Flexible remote work', 'Annual conference travel stipend', 'Top-tier tech setup', 'Global team retreats'],
    websiteUrl: 'https://postman.com',
    careersUrl: 'https://postman.com/careers',
    socialLinks: {
      linkedin: 'https://linkedin.com/company/postman-platform',
      twitter: 'https://twitter.com/getpostman',
      github: 'https://github.com/postmanlabs',
    },
    stats: {
      openJobsCount: 6,
      openInternshipsCount: 2,
      hackathonsCount: 2,
      totalOpportunities: 10,
    },
    isVerified: true,
    isHiring: true,
  },
  {
    id: 'comp-4',
    slug: 'cred',
    name: 'CRED',
    domain: 'cred.club',
    logoUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=128&h=128&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=1200&h=400&fit=crop',
    industry: 'Fintech / Consumer',
    headquarters: 'Bengaluru, Karnataka, India',
    size: '800–1,500 employees',
    foundedYear: 2018,
    about: 'CRED is an exclusive members-only community celebrating high-trust individuals with premium financial services and rewards.',
    culture: 'High standards, product obsession, craftsmanship, and minimal bureaucracy.',
    perks: ['Comprehensive healthcare for family', 'Unlimited paid leave', 'Subsidized food & fitness', 'Cutting edge hardware'],
    websiteUrl: 'https://cred.club',
    careersUrl: 'https://careers.cred.club',
    socialLinks: {
      linkedin: 'https://linkedin.com/company/cred-club',
      twitter: 'https://twitter.com/cred_club',
    },
    stats: {
      openJobsCount: 5,
      openInternshipsCount: 1,
      hackathonsCount: 0,
      totalOpportunities: 6,
    },
    isVerified: true,
    isHiring: true,
  },
];

export const SEED_JOBS: Job[] = [
  {
    id: 'job-1',
    slug: 'swiggy-senior-backend-engineer-distributed-systems',
    title: 'Senior Backend Engineer — Distributed Systems',
    company: {
      id: 'comp-1',
      name: 'Swiggy',
      slug: 'swiggy',
      logoUrl: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=128&h=128&fit=crop',
      websiteUrl: 'https://swiggy.com',
      verified: true,
      industry: 'Consumer Tech',
      location: 'Bengaluru, Karnataka, India',
    },
    location: 'Bengaluru, Karnataka, India',
    country: 'India',
    city: 'Bengaluru',
    workplaceType: 'hybrid',
    employmentType: 'full-time',
    seniority: 'senior',
    experienceYears: { min: 4, max: 8 },
    salary: {
      min: 3200000,
      max: 5500000,
      currency: 'INR',
      period: 'year',
      formatted: '₹32L – ₹55L/yr',
      isNegotiable: true,
    },
    skills: ['Go', 'Java', 'Distributed Systems', 'Kafka', 'PostgreSQL', 'Redis', 'Kubernetes'],
    description: 'We are seeking an experienced Backend Engineer to scale our core order-dispatch and real-time inventory systems handling 3M+ orders daily with sub-50ms latency.',
    responsibilities: [
      'Architect and implement high-throughput, low-latency microservices using Go and Java.',
      'Optimize database queries and streaming data pipelines with Kafka and Redis.',
      'Lead design reviews and mentor junior engineering team members.',
    ],
    requirements: [
      '4+ years of professional backend software development experience.',
      'Demonstrated expertise in distributed caching, message queues, and high-concurrency architectures.',
      'Strong problem-solving and algorithmic skills.',
    ],
    benefits: ['Comprehensive health insurance', 'ESOP grants', 'Annual learning budget', 'Flexible hybrid policy'],
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    applyUrl: 'https://careers.swiggy.com/jobs/senior-backend-distributed',
    sourceUrl: 'https://careers.swiggy.com',
    sourcePlatform: 'greenhouse',
    isFeatured: true,
    viewsCount: 1840,
    applicantsCount: 76,
  },
  {
    id: 'job-2',
    slug: 'razorpay-software-development-engineer-2-frontend',
    title: 'Software Development Engineer II — Frontend',
    company: {
      id: 'comp-2',
      name: 'Razorpay',
      slug: 'razorpay',
      logoUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=128&h=128&fit=crop',
      websiteUrl: 'https://razorpay.com',
      verified: true,
      industry: 'Fintech',
      location: 'Bengaluru, Karnataka, India',
    },
    location: 'Bengaluru, Karnataka, India',
    country: 'India',
    city: 'Bengaluru',
    workplaceType: 'hybrid',
    employmentType: 'full-time',
    seniority: 'mid',
    experienceYears: { min: 2, max: 5 },
    salary: {
      min: 2400000,
      max: 4000000,
      currency: 'INR',
      period: 'year',
      formatted: '₹24L – ₹40L/yr',
      isNegotiable: false,
    },
    skills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS', 'Web Performance', 'Design Systems'],
    description: 'Join the Razorpay Checkout team to build seamless, high-converting payment checkout experiences used by hundreds of millions of consumers across India.',
    responsibilities: [
      'Build lightning-fast, accessible checkout interfaces with React and TypeScript.',
      'Maintain and extend our core UI component design system.',
      'Collaborate closely with product designers, QA, and security auditors.',
    ],
    requirements: [
      '2+ years of production experience building modern web applications with React & TypeScript.',
      'Deep understanding of browser rendering performance, Core Web Vitals, and responsive UI.',
      'Passion for pixel-perfect design and high-standard UI craft.',
    ],
    benefits: ['ESOP equity program', 'MacBook Pro M3 Max provided', 'Full medical insurance', 'WFH ergonomics allowance'],
    postedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    applyUrl: 'https://razorpay.com/jobs/sde2-frontend',
    sourceUrl: 'https://razorpay.com/jobs',
    sourcePlatform: 'lever',
    isFeatured: true,
    viewsCount: 2410,
    applicantsCount: 112,
  },
  {
    id: 'job-3',
    slug: 'postman-staff-software-engineer-api-platform',
    title: 'Staff Software Engineer — API Platform Core',
    company: {
      id: 'comp-3',
      name: 'Postman',
      slug: 'postman',
      logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&h=128&fit=crop',
      websiteUrl: 'https://postman.com',
      verified: true,
      industry: 'Developer Tools',
      location: 'Bengaluru / Remote',
    },
    location: 'Remote (India)',
    country: 'India',
    city: 'Remote',
    workplaceType: 'remote',
    employmentType: 'full-time',
    seniority: 'lead',
    experienceYears: { min: 8 },
    salary: {
      min: 6000000,
      max: 9500000,
      currency: 'INR',
      period: 'year',
      formatted: '₹60L – ₹95L/yr',
      isNegotiable: true,
    },
    skills: ['Node.js', 'TypeScript', 'Rust', 'GraphQL', 'System Architecture', 'Cloud Infrastructure'],
    description: 'Postman is looking for a Staff Engineer to drive architecture decisions across our global API gateway, sync protocols, and real-time collaboration engines.',
    responsibilities: [
      'Define long-term architectural roadmaps for Postman core backend services.',
      'Lead company-wide technical strategy for performance and reliability.',
      'Advise executive engineering leadership on platform modernization.',
    ],
    requirements: [
      '8+ years building hyperscale developer or cloud platforms.',
      'Proven track record leading complex technical architectures across distributed teams.',
    ],
    benefits: ['100% remote flexibility', 'Top compensation & equity', 'Annual retreat travel', 'Unlimited paid time off'],
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    applyUrl: 'https://postman.com/careers/staff-core-platform',
    sourceUrl: 'https://postman.com/careers',
    sourcePlatform: 'ashby',
    isFeatured: true,
    viewsCount: 1290,
    applicantsCount: 34,
  },
  {
    id: 'job-4',
    slug: 'cred-security-engineer-cloud-infrastructure',
    title: 'Security Engineer — Cloud & Infrastructure',
    company: {
      id: 'comp-4',
      name: 'CRED',
      slug: 'cred',
      logoUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=128&h=128&fit=crop',
      websiteUrl: 'https://cred.club',
      verified: true,
      industry: 'Fintech',
      location: 'Bengaluru, Karnataka, India',
    },
    location: 'Bengaluru, Karnataka, India',
    country: 'India',
    city: 'Bengaluru',
    workplaceType: 'onsite',
    employmentType: 'full-time',
    seniority: 'senior',
    experienceYears: { min: 4, max: 7 },
    salary: {
      min: 3500000,
      max: 6000000,
      currency: 'INR',
      period: 'year',
      formatted: '₹35L – ₹60L/yr',
      isNegotiable: false,
    },
    skills: ['AWS Security', 'Kubernetes Security', 'Terraform', 'DevSecOps', 'SIEM', 'Penetration Testing'],
    description: 'CRED is looking for a Security Engineer to defend our mission-critical banking integrations and zero-trust cloud infrastructure.',
    responsibilities: [
      'Build automated security compliance pipelines across AWS and multi-cluster Kubernetes.',
      'Conduct threat modeling, architecture reviews, and red team exercises.',
    ],
    requirements: [
      '4+ years hands-on cloud and container security experience in high-security environments.',
      'Demonstrated expertise in IAM, network segmentation, and automated vulnerability scanning.',
    ],
    benefits: ['Competitive compensation', 'Premium cafeteria meals', 'Comprehensive health coverage', 'Gym membership'],
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    applyUrl: 'https://careers.cred.club/security-eng',
    sourceUrl: 'https://careers.cred.club',
    sourcePlatform: 'workday',
    isFeatured: false,
    viewsCount: 940,
    applicantsCount: 29,
  },
];

export const SEED_INTERNSHIPS: Internship[] = [
  {
    id: 'intern-1',
    slug: 'razorpay-software-engineering-intern-summer-2026',
    title: 'Software Engineering Intern — Summer 2026',
    company: {
      id: 'comp-2',
      name: 'Razorpay',
      slug: 'razorpay',
      logoUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=128&h=128&fit=crop',
      websiteUrl: 'https://razorpay.com',
      verified: true,
      industry: 'Fintech',
      location: 'Bengaluru, Karnataka, India',
    },
    location: 'Bengaluru, Karnataka, India',
    country: 'India',
    city: 'Bengaluru',
    workplaceType: 'hybrid',
    stipend: {
      min: 75000,
      max: 85000,
      currency: 'INR',
      period: 'month',
      formatted: '₹75,000 – ₹85,000/mo',
      isPerformanceBased: false,
    },
    duration: {
      value: 6,
      unit: 'months',
      formatted: '6 months',
    },
    startDate: '2026-06-01',
    isImmediate: false,
    applicationDeadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    skills: ['Java', 'Spring Boot', 'MySQL', 'Data Structures', 'Algorithms'],
    description: 'Work directly on high-scale payment processing pipelines alongside principal engineers with a direct Pre-Placement Offer (PPO) evaluation for top performers.',
    perks: ['Pre-Placement Offer (PPO) opportunities', 'Stipend ₹80,000/month', 'Relocation & accommodation allowance', '1:1 Principal Engineer mentorship'],
    ppoOffered: true,
    eligibility: ['B.Tech / M.Tech / Dual Degree students graduating in 2026 or 2027', 'Strong fundamentals in OOP, DSA, and databases'],
    responsibilities: [
      'Design, build, and test features for high-volume banking transaction workflows.',
      'Participate in daily engineering scrums, design reviews, and code deployments.',
    ],
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    applyUrl: 'https://razorpay.com/jobs/intern-summer-2026',
    sourceUrl: 'https://razorpay.com/jobs',
    sourcePlatform: 'lever',
    isFeatured: true,
    viewsCount: 3120,
    applicantsCount: 245,
  },
  {
    id: 'intern-2',
    slug: 'swiggy-product-design-intern-instamart',
    title: 'Product Design Intern — Instamart Quick Commerce',
    company: {
      id: 'comp-1',
      name: 'Swiggy',
      slug: 'swiggy',
      logoUrl: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=128&h=128&fit=crop',
      websiteUrl: 'https://swiggy.com',
      verified: true,
      industry: 'Consumer Tech',
      location: 'Bengaluru, Karnataka, India',
    },
    location: 'Bengaluru, Karnataka, India',
    country: 'India',
    city: 'Bengaluru',
    workplaceType: 'onsite',
    stipend: {
      min: 50000,
      max: 65000,
      currency: 'INR',
      period: 'month',
      formatted: '₹50,000 – ₹65,000/mo',
      isPerformanceBased: false,
    },
    duration: {
      value: 3,
      unit: 'months',
      formatted: '3 months',
    },
    startDate: 'immediate',
    isImmediate: true,
    applicationDeadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    skills: ['Figma', 'UI/UX Design', 'User Research', 'Prototyping', 'Design Systems'],
    description: 'Help shape the quick-commerce shopping experience for 50M+ Indians across grocery, electronics, and daily essentials on Swiggy Instamart.',
    perks: ['PPO consideration', 'Free Swiggy One membership', 'Dedicated mentor'],
    ppoOffered: true,
    eligibility: ['Design students or self-taught designers with strong portfolio', 'Proficiency in Figma and interactive prototyping'],
    responsibilities: [
      'Conduct user research sessions and synthesize usability insights.',
      'Create high-fidelity wireframes and design system components.',
    ],
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    applyUrl: 'https://careers.swiggy.com/jobs/design-intern',
    sourceUrl: 'https://careers.swiggy.com',
    sourcePlatform: 'greenhouse',
    isFeatured: true,
    viewsCount: 1650,
    applicantsCount: 98,
  },
  {
    id: 'intern-3',
    slug: 'postman-developer-relations-intern',
    title: 'Developer Relations & Technical Content Intern',
    company: {
      id: 'comp-3',
      name: 'Postman',
      slug: 'postman',
      logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&h=128&fit=crop',
      websiteUrl: 'https://postman.com',
      verified: true,
      industry: 'Developer Tools',
      location: 'Remote',
    },
    location: 'Remote (India)',
    country: 'India',
    city: 'Remote',
    workplaceType: 'remote',
    stipend: {
      min: 45000,
      max: 60000,
      currency: 'INR',
      period: 'month',
      formatted: '₹45,000 – ₹60,000/mo',
      isPerformanceBased: false,
    },
    duration: {
      value: 6,
      unit: 'months',
      formatted: '6 months',
    },
    startDate: 'immediate',
    isImmediate: true,
    applicationDeadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    skills: ['APIs', 'Technical Writing', 'JavaScript', 'Public Speaking', 'Community Engagement'],
    description: 'Create technical tutorials, host workshops, and engage with the global community of 30M+ developers building with Postman APIs.',
    perks: ['100% remote flexibility', 'Certificate of Completion', 'Postman swag package', 'Global developer network visibility'],
    ppoOffered: false,
    eligibility: ['College students actively involved in developer clubs, hackathons, or open source', 'Familiarity with REST APIs and Postman'],
    responsibilities: [
      'Write sample API collections and interactive tutorials.',
      'Speak at college hackathons and developer meetups.',
    ],
    postedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    applyUrl: 'https://postman.com/careers/devrel-intern',
    sourceUrl: 'https://postman.com/careers',
    sourcePlatform: 'ashby',
    isFeatured: false,
    viewsCount: 2200,
    applicantsCount: 160,
  },
];

export const SEED_HACKATHONS: Hackathon[] = [
  {
    id: 'hack-1',
    slug: 'ethindia-2026-asia-biggest-web3-hackathon',
    title: 'ETHIndia 2026 — Asia’s Biggest Ethereum Hackathon',
    organizer: {
      name: 'Devfolio & ETHGlobal',
      logoUrl: 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?w=128&h=128&fit=crop',
      websiteUrl: 'https://ethindia.co',
      verified: true,
    },
    mode: 'offline',
    location: 'KTPO, Whitefield, Bengaluru, India',
    city: 'Bengaluru',
    country: 'India',
    registrationDeadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
    startDate: new Date(Date.now() + 24 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 26 * 24 * 60 * 60 * 1000).toISOString(),
    prizePool: {
      total: 10000000,
      currency: 'INR',
      formatted: '₹1,00,00,000 ($120k+)',
      prizes: [
        { title: 'Grand Winner', amount: 2500000, currency: 'INR', description: 'Overall best hackathon project' },
        { title: '1st Runner Up', amount: 1500000, currency: 'INR', description: 'Second place overall' },
        { title: 'Track Winners (DeFi, AI, ZK, Infra)', amount: 6000000, currency: 'INR', description: 'Sponsored track pool bounties' },
      ],
    },
    teamSize: { min: 2, max: 4, formatted: '2–4 members' },
    eligibility: 'Open to all developers, researchers, and students globally. Free registration with curated hacker selection.',
    themes: ['Web3 & DeFi', 'Artificial Intelligence & Zero Knowledge', 'Decentralized Social', 'Developer Tooling'],
    technologies: ['Solidity', 'Rust', 'TypeScript', 'Next.js', 'PyTorch', 'Zero Knowledge Proofs'],
    tags: ['Ethereum', 'AI Agents', 'Open Source', 'Hackathon'],
    description: 'ETHIndia brings together 2,000+ top builders, protocol designers, and investors from across the globe for 36 hours of non-stop coding, networking, and innovation.',
    rules: [
      'All code must be written during the official 36-hour hacking period.',
      'Teams must consist of 2 to 4 members.',
      'Projects must be open source with a public GitHub repository and working demo video.',
    ],
    timeline: [
      { title: 'Applications Close', date: 'In 18 days', completed: false },
      { title: 'Hacker Check-in & Opening Ceremony', date: 'In 24 days', completed: false },
      { title: 'Hacking Concludes & Project Demos', date: 'In 26 days', completed: false },
    ],
    sponsors: [
      { name: 'Ethereum Foundation', tier: 'title' },
      { name: 'Polygon Labs', tier: 'platinum' },
      { name: 'Chainlink', tier: 'gold' },
    ],
    status: 'open',
    applyUrl: 'https://ethindia.co/apply',
    officialUrl: 'https://ethindia.co',
    bannerUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&h=400&fit=crop',
    sourcePlatform: 'devfolio',
    isFeatured: true,
    participantsCount: 4200,
    viewsCount: 18900,
  },
  {
    id: 'hack-2',
    slug: 'flipkart-grid-7-0-national-engineering-challenge',
    title: 'Flipkart GRiD 7.0 — National Engineering Challenge',
    organizer: {
      name: 'Flipkart',
      logoUrl: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=128&h=128&fit=crop',
      websiteUrl: 'https://unstop.com',
      verified: true,
    },
    mode: 'online',
    location: 'Online (National)',
    city: 'Online',
    country: 'India',
    registrationDeadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    startDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    prizePool: {
      total: 1500000,
      currency: 'INR',
      formatted: '₹15,00,000 + SDE Job Offers',
      prizes: [
        { title: 'National Winners', amount: 500000, currency: 'INR', description: 'Top team + PPI/PPO' },
        { title: 'Runners Up', amount: 300000, currency: 'INR', description: 'Second team + PPI' },
      ],
    },
    teamSize: { min: 2, max: 3, formatted: '2–3 members' },
    eligibility: 'B.Tech / B.E. / M.Tech / Dual Degree students from all AICTE/UGC recognized engineering colleges in India.',
    themes: ['Generative AI in E-Commerce', 'Smart Supply Chain Robotics', 'Real-Time Fraud Prevention'],
    technologies: ['Python', 'TensorFlow', 'Java', 'Distributed Systems', 'Computer Vision'],
    tags: ['E-Commerce', 'Flipkart', 'Job Offers', 'National Contest'],
    description: 'Flipkart’s flagship engineering challenge for university students, featuring real-world problems in e-commerce and direct interview calls for SDE-1 roles with ₹32 LPA packages.',
    status: 'open',
    applyUrl: 'https://unstop.com/hackathons/flipkart-grid-7',
    officialUrl: 'https://unstop.com',
    bannerUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&h=400&fit=crop',
    sourcePlatform: 'unstop',
    isFeatured: true,
    participantsCount: 22000,
    viewsCount: 35000,
  },
];

export const SEED_CONTESTS: Contest[] = [
  {
    id: 'contest-1',
    slug: 'codeforces-round-1002-div-2',
    name: 'Codeforces Round 1002 (Div. 2)',
    platform: 'Codeforces',
    organizer: 'Codeforces Community',
    platformLogoUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=128&h=128&fit=crop',
    startTime: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
    durationMinutes: 120,
    durationFormatted: '2 hours',
    ratingType: 'Div 2',
    difficulty: 'intermediate',
    participantsCount: 16500,
    status: 'UPCOMING',
    eligibility: 'Rated for participants with rating strictly below 2100',
    officialUrl: 'https://codeforces.com/contests',
    description: 'Standard 6-problem algorithmic competition with interactive problems and runtime evaluation.',
    problemCount: 6,
    languagesAllowed: ['C++', 'Python 3', 'Java', 'Rust', 'Go', 'Kotlin'],
    prizes: 'Rating changes & badge achievements',
    isBookmarked: false,
  },
  {
    id: 'contest-2',
    slug: 'leetcode-weekly-contest-438',
    name: 'Weekly Contest 438',
    platform: 'LeetCode',
    organizer: 'LeetCode',
    platformLogoUrl: 'https://images.unsplash.com/photo-1516116211227-bbc03e33c7f6?w=128&h=128&fit=crop',
    startTime: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000 + 90 * 60 * 1000).toISOString(),
    durationMinutes: 90,
    durationFormatted: '1h 30m',
    ratingType: 'Rated',
    difficulty: 'all-levels',
    participantsCount: 28000,
    status: 'UPCOMING',
    eligibility: 'Open to all registered LeetCode users',
    officialUrl: 'https://leetcode.com/contest/',
    description: '4 algorithm challenges ranging from Easy to Hard. Solve under 90 minutes to boost your global LeetCode contest rating.',
    problemCount: 4,
    languagesAllowed: ['C++', 'Java', 'Python', 'JavaScript', 'TypeScript', 'Go'],
    prizes: 'LeetCoins and global profile badges',
    isBookmarked: false,
  },
  {
    id: 'contest-3',
    slug: 'codechef-starters-175-div-1-2-3-4',
    name: 'Starters 175 (Rated till 6-Stars)',
    platform: 'CodeChef',
    organizer: 'CodeChef',
    platformLogoUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=128&h=128&fit=crop',
    startTime: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
    durationMinutes: 120,
    durationFormatted: '2 hours',
    ratingType: 'Rated',
    difficulty: 'all-levels',
    participantsCount: 14200,
    status: 'UPCOMING',
    eligibility: 'Rated for Divisions 1, 2, 3, and 4',
    officialUrl: 'https://codechef.com/contests',
    description: 'Weekly Wednesday contest designed to help competitive programmers sharpen algorithmic problem solving.',
    problemCount: 7,
    languagesAllowed: ['C++', 'Python', 'Java', 'C'],
    prizes: 'CodeChef Laddus & ratings',
    isBookmarked: false,
  },
];
